config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :categories
  resources :sections
  resources :cities
	root to: 'sections#index'
	get 'sections/show_categories'
  get 'sections/:id/show_categories', to: 'sections#show_categories'
	get 'categories/:id/show_posts', to: 'categories#show_posts', as: 'category_show_posts'
	get 'cities/:id/show_posts', to: 'cities#show_posts', as: 'city_show_posts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :categories
	validates :name, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy, :show_categories]
	skip_before_action :authenticate_user!, only: [:index]
	skip_before_action :deny_access, only: [:index]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
		@cities = City.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end
	
	def show_categories
		render json: @section.categories
		
	end
	
	def show_posts
		render json: @section.categories	
	end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_cities.html.erb
<div id="rightbar">

<ul class="menu collapsible">
	<li class="expand s">
		<h5 class="ban hot active">US Cities</h5>
		<ul class="acitem" style="display: block;">
			 <% @cities.each do |city| %>
<li class="s"><a href="<%= city_show_posts_path(city.id) %>"><%= city.name %></a></li>
			<% end %>
</li>
	</ul>
</li>
	      </ul>
        
    
 </div>

app/views/sections/_example.html.erb
<div id="center">
	
	 <% @sections.each do |section| %>
	            <div class="<%= section.name %>">
                
        <div id="ccc" class="col">
        <h4 class="ban"><a href="/d/community/search/ccc" class="ccc" data-alltitle="all <%= section.name %>" data-cat="ccc"><span class="txt"><%= section.name %><sup class="c"></sup></span></a></h4>
        <div class="cats">
        <ul id="ccc0" class="left">
					<% section.categories.each do |category| %>
	<li><a href="<%= category_show_posts_path(category.id) %>" class="<%= category.name %>" data-cat="<%= category.name %>"><span class="txt"><%= category.name %><sup class="c"></sup></span></a></li>				
					<% end %>
</ul>
	
	
	<% end %>
	

<!--					
<ul id="ccc1" class="mc">
<li><a href="/d/lost-found/search/laf" class="laf" data-cat="laf"><span class="txt">lost+found<sup class="c"></sup></span></a></li>
<li><a href="/d/missed-connections/search/mis" class="mis" data-cat="mis"><span class="txt">missed connections<sup class="c"></sup></span></a></li>
<li><a href="/d/musicians/search/muc" class="muc" data-cat="muc"><span class="txt">musicians<sup class="c"></sup></span></a></li>
<li><a href="/d/pets/search/pet" class="pet" data-cat="pet"><span class="txt">pets<sup class="c"></sup></span></a></li>
<li><a href="/d/politics/search/pol" class="pol" data-cat="pol"><span class="txt">politics<sup class="c"></sup></span></a></li>
<li><a href="/d/rants-raves/search/rnr" class="rnr" data-cat="rnr"><span class="txt">rants &amp; raves<sup class="c"></sup></span></a></li>
<li><a href="/d/rideshare/search/rid" class="rid" data-cat="rid"><span class="txt">rideshare<sup class="c"></sup></span></a></li>
<li><a href="/d/volunteers/search/vol" class="vol" data-cat="vol"><span class="txt">volunteers<sup class="c"></sup></span></a></li>
</ul>

-->
</div>
</div>

         </div>
</div>

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/_leftbar.html.erb
<div id="leftbar">
            <div id="logo">
    <a href="#">CRAIGSLIST</a>
</div>

<ul id="postlks">
		<% if user_signed_in? %>
  <li><a href="#">Logged in as <strong><%= current_user.email %></a></strong></li>
  <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
<% else %>
  <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
  <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
<% end %>
	
    <li><a id="post" href="https://post.craigslist.org/c/phi">create a posting</a></li>
</ul>

	
	
	<!--
<form id="search" class="homepage-search" action="/search/" method="GET">
    <input type="hidden" name="sort" value="rel">
    <input type="hidden" name="ordinal" id="ordinal" value="1">
    <input type="hidden" name="ratio" id="ratio" value="0">
    <input type="hidden" name="clicked" id="clicked" value="0">
    <input id="query" class="querybox flatinput ui-autocomplete-input" name="query" data-autocomplete="search-count" autocorrect="off" autocapitalize="off" placeholder="search craigslist" autofocus="autofocus" autocomplete="off">
    <select id="catAbb" name="catAbb" class="homepage-category-picker">
        <option value="" selected="selected">select category</option>
        <option value="ccc">community</option>
        <option value="eee">events</option>
        <option value="ggg">gigs</option>
        <option value="hhh">housing</option>
        <option value="jjj">jobs</option>
        <option value="rrr">resumes</option>
        <option value="sss">for sale</option>
        <option value="bbb">services</option>
    </select>
    <button type="submit" id="go" class="searchbtn"><span class="icon icon-search"><span class="screen-reader-text">search craigslist</span></span></button>
</form> -->

        </div>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<%= render 'leftbar' %>
<%= render 'example' %>
<%= render 'cities' %>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>